#! /usr/bin/env bash
. $(dirname $0)/logging.sh

fifo=$(dirname $0)/$$.fifo
mkfifo $fifo
trap "rm $fifo" EXIT

echo $fifo
exec {fifofd}<$fifo

function init {
    file=$1
    cont=$2
    agas=${@:3}
    maxi=$(ag $agas $file | wc -l)
    curi=0
    next
}

function next {
    curi=$(($curi % $maxi + 1))
    rang="rmin = \$1 - $cont/2; rmax = \$1 + $cont/2; if (rmin < 1) { rmax -= (rmin - 1); rmin = 1; }  printf \"-r %d:%d -H %d\", rmin, rmax, \$1"
    bata=$(ag --numbers $agas $file | awk -F: "FNR == $curi { $rang }")
    echo "OK"
}

function preview {
    bat -n --color=always $bata $file
}

function getSelectedLineNumber {
    line=$(ag --numbers $agas $file | awk -F: "FNR == $curi { print \$1 }")
    echo $line
}

while read -u $fifofd responseFifo cmd args; do
    case $cmd in
        "init") init $args > $responseFifo;;
        "next") next > $responseFifo;;
        "preview") preview > $responseFifo;;
        "getSelectedLineNumber") getSelectedLineNumber > $responseFifo;;
        *) echo OpGrepServer does not recognize command $cmd > $responseFifo;;
    esac
done
