#! /usr/bin/env bash
. $(dirname $0)/logging.sh

fifo=$1
exec {fifofd}>$fifo

responseFifo=$(dirname $0)/$$.fifo
mkfifo $responseFifo
trap "rm $responseFifo" EXIT

while read cmd; do
    echo $responseFifo $cmd >&$fifofd
    exec {responseFifofd}<$responseFifo
    while read -u $responseFifofd response; do
       echo $response
    done
    exec {responseFifofd}<&-
done
