#! /usr/bin/env bash
socket=$1
function request {
    echo "init OpGrepServer 10 function" && sleep 1
    echo "next" && sleep 1
    echo "next" && sleep 1
}
request | nc -U "$socket"
$(dirname $0)/Request $socket "get"
