#! /usr/bin/env bash

rund=$(dirname $0)/run
mkdir -p "$rund"
. ~/.sh/logging.sh "$rund"

path=$1
width=$2
height=$3

out1="$rund/$$.1.tmp"
out2="$rund/$$.2.tmp"
out3="$rund/$$.3.tmp"
touch $out1
touch $out2
touch $out3
trap "rm $out1; rm $out2; rm $out3" EXIT

function filteredLs {
    ls -pA1 $1 | grep -v -e ".swp$" -e "^Session.vim$"
}

function printToNeedle {
    need=$1
    levl=$2
    if [[ $levl -eq 0 ]]; then
        nop="  "
        nep=" •"
    else
        nop="│ "
        nep="╰•"
    fi
    prin='$0==n { s=e; h=sprintf("%*s",w,"") } 1 { i=sprintf("%*.*s", l+2, l+2, ""); print i s $0 h; if (s!=o) exit }'
    awk -v n=$need -v s="$nop" -v e="$nep" -v o="$nop" -v l=$levl -v w=$width "$prin"
}

function printToEnd {
    need=$1
    levl=$2
    prin='BEGIN { i=sprintf("%*.*s", l+2, l+2, " ") } 1 { if (p) print i $0 } $0==n { p=1 }'
    awk -v n=$need -v l="$levl" "$prin"
}

function fillOut {
    dir=$1
    printer=$2
    out=$3
}

function previewRec {
    local dir=$1
    local levl="${2:-0}"
    local next;
    if read next; then
        filteredLs $dir | printToNeedle $next $levl | cut -c 1-$width > $out3
        if [[ $next == */ ]]; then
            cat $out3 >> $out1
            previewRec "$dir/${next%/}" $(($levl + 1)) 
        else
            cat $out3 | sed '$d' >> $out1
            tail -n 1 $out3 | awk '{ print "\033[48;5;237m" $0 "\033[0m" }' >> $out1
        fi
        filteredLs $dir | printToEnd $next $levl | cut -c 1-$width >> $out2
    fi
}

echo $path | sed 's#/#/\n#g' | previewRec '.'
context=$(($height / 2))
before=$(wc -l < $out1)
after=$(wc -l < $out2)
if [[ $context -lt $after ]]; then
    after=$context
fi
if [[ $context -gt $before ]]; then
    after=$(($after + ($context - $before)))
else
    before=$(($context + $height % 2))
fi
[[ $before -gt 0 ]] && tail -n $before $out1
[[ $after -gt 0 ]] && head -n $after $out2
