#! /usr/bin/env bash
. $(dirname $0)/logging.sh

fifo=$(dirname $0)/$$.fifo
mkfifo $fifo
trap "rm $fifo" EXIT

echo $fifo
exec {fifofd}<>$fifo

function init {
    path=$1
    width=$2
    height=$3
    echo "OK"
}

function setPath {
    path=$1
    echo "OK"
}

function preview {
    if [[ -z $height ]]; then
        echo "Loading preview..."
    elif [[ -z $path ]]; then
        $(dirname $0)/explorer $width $height
    else
        $(dirname $0)/explorer $path $width $height
    fi
}

function previewToStdout {
    responseFifo=$1
    tput clear
    preview
    echo "OK" > $responseFifo
}

while read -u $fifofd responseFifo cmd args; do
    case $cmd in
        "init") init $args > $responseFifo;;
        "setPath") setPath $args > $responseFifo;;
        "preview") preview > $responseFifo;;
        "previewToStdout") previewToStdout $responseFifo;;
        *) echo OpOpenServer does not recognize command $cmd > $responseFifo;;
    esac
done
