#! /usr/bin/env bash
rund=$(dirname $0)/run
mkdir -p "$rund"

fifo=$1
responseFifo="$rund/$$.fifo"
mkfifo $responseFifo
trap "rm $responseFifo" EXIT

printf "%q " $responseFifo "${@:2}" > $fifo
printf "\n" > $fifo
cat $responseFifo
