#!/usr/bin/env bash

. $(dirname $0)/logging.sh

path=$1
width=$2
cols=$(echo $path | awk -F/ '{print NF}')
if [[ $cols -lt 1 ]]; then
    echo $path
    exit
fi
colw=$((($width - ($cols - 1)) / $cols - 2))
if [[ $colw -lt 4 ]]; then
    if [[ $cols -gt 1 ]]; then
        rerun=$(realpath $0)
        cd ${path%%/*}
        $rerun ${path#*/} $width
        exit
    fi
    echo "not enough space to fit a single column..."
    exit
fi

while [[ ${#clws[@]} -lt $((width%cols)) ]]; do clws+=($(($colw + 1))); done
while [[ ${#clws[@]} -lt $cols ]]; do clws+=($colw); done

dirs=$(echo $path | awk -F/ '{ s="."; for (i=1; i<=NF; ++i) { for (j=1; j<i; ++j) s = s "/" $j; print s; s = "." } }')
fifs=$(echo $dirs | xargs -n 1 | awk '{print "lspathfifo" NR}')

echo "$fifs" | xargs -n 1 mkfifo
(
trap "echo \"$fifs\" | xargs -n 1 rm" EXIT

function filteredLs {
    (cd $1 && find . -mindepth 1 -maxdepth 1 '!' -name '*.swp' -print | ls -pA1)
}

paste <(echo $dirs | xargs -n 1) <(echo $fifs | xargs -n 1) | while read d f; do filteredLs $d > $f; done &

grid='grid["", ""] = " "; grid["", 1] = "┌"; grid["", 2] = "│"; grid[1, ""] = "┐"; grid[1, 1] = "─"; grid[1, 2] = "┘"; grid[2, ""] = "│"; grid[2, 1] = "└"; grid[2, 2] = " "'
elem="for (i=1; i<=NF; ++i) { elem[i] = sprintf(\" %-${colw}.${colw}s \", \$i); if (\$i == nees[i]) { gsub(\" \", \"─\", elem[i]); done[i] = 1; } else if (done[i] == 1) done[i] = 2 }"
sepr='for (i=1; i<NF; ++i) { sepr = grid[done[i], done[i + 1]]; printf "%s%s", elem[i], sepr } printf "%s", elem[NF]'
echo $fifs | xargs paste -d":" | awk -F: -v p=$path "BEGIN { gsub(\"/\", \"/:\", p); split(p, nees, \":\"); $grid; } { $elem; $sepr; printf \"\\n\" }"
)

