#! /usr/bin/env bash
rund="$(dirname $0)/run"
mkdir -p "$rund"
. ~/.sh/logging.sh "$rund"

socket=$rund/$$.socket
trap "rm $socket" EXIT

function init {
    width=$1
    height=$2
}

function previewWithPath {
    if [[ -z $height ]]; then
        echo "Explorer not yet initialized..."
        return
    fi
    tput clear
    $(dirname $0)/Explorer $1 $width $height
}

function mainLoop {
    while read cmd args; do
        case $cmd in
            "init") init $args ;;
            "previewWithPath") previewWithPath $args ;;
            *) echo ExplorerServer does not recognize command $cmd ;;
        esac
    done
}

nc -kUl $socket | mainLoop
