#! /usr/bin/env bash

rund=$(realpath $(dirname $0))/run
mkdir -p "$rund"
. ~/.sh/logging.sh "$rund"

if ! tmux has-session 2>/dev/null; then
    tmux -2 new "$0 $*"
    exit
fi

if [[ $1 != ":here:" ]]; then
    tmux -2 new-window "$0 ':here:' $*"
    exit
else
    shift
fi

cd $1
sess=$2

mkfifo "$rund/$$.fifo"

side=20
bot=7

exec {opFileServerfd}< <(~/.sh/OpFileServer)
opFileServerPid=$!
read opFileServerFifo <&$opFileServerfd
tmux split-window -hdIP -l $((2 * $side + 2)) -F "#{pane_index} #{pane_height}" <&$opFileServerfd >"$rund/$$.fifo" &
read opFileServerPaneId h <"$rund/$$.fifo"

echo "$rund/$$.fifo" "init" "." "20" "$(($h - $bot - 2))" > $opFileServerFifo
read < "$rund/$$.fifo"
echo "$rund/$$.fifo" "previewToStdout" > $opFileServerFifo
read < "$rund/$$.fifo"

tmux split-window -dI -t $opFileServerPaneId -l $bot < <(cat <(tail -n 1 $sess | xargs printf "\033[48;5;237m%-41.41s\033[0m\n") <(tac $sess | head -n $bot | sed '1d' | cut -c 1-41))

tmux split-window -hdPb -t $opFileServerPaneId -l $side -F "#{pane_pid} #{pane_width} #{pane_height}" "~/.sh/MinimapServer" >"$rund/$$.fifo" &
read minimapServerPid minimapWidth minimapHeight <"$rund/$$.fifo"
minimapServerSocket="$rund/$minimapServerPid.socket"
while ! [[ -e "$minimapServerSocket" ]]; do sleep 0.1s; done 

function cleanup {
    kill $opFileServerPid
    rm "$rund/$$.fifo"
    tmux kill-window
}
trap cleanup EXIT

sessionVim="$(dirname $sess)/vim-sessions/$(pwd | sed 's#/#ESCAPED_SLASH#g').vim"
[[ -e $sessionVim ]] && sessionOption="-S $sessionVim"
vim $sessionOption \
    --cmd "let g:codeSessionsFile=\"$sess\""\
    --cmd "let g:codeFileServerFifo=\"$opFileServerFifo\""\
    --cmd "let g:codeMinimapWidth=\"$minimapWidth\""\
    --cmd "let g:codeMinimapHeight=\"$minimapHeight\""\
    --cmd "let g:codeMinimapServerSocket=\"$minimapServerSocket\""
